inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style/FrozenStringLiteralComment:
#   Enabled: false
